### ISSUE TITLE
Use additionalProperties and required attributes uniformly

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#289] opened 2021-04-30 14:22 UTC
The schema used additionalProperties and required attributes inconsistently. That led to their removal. However, move significantly lessens the validation strictness of the schema. These properties should be reintroduced.

~At the same time, clarify use of null. In particular, decide whether null is a valid value, and, if so, how explicit null, default null, additionalProperties, and required attributes are related.~ Also see `null` value discussion occurring in #275.

**Comment by ahwagner** [comment] 2021-04-30 19:54
Duplicate of #275

**Comment by ahwagner** [comment] 2021-04-30 20:27
repurposing this issue to be non-duplicate and focus explicitly on the question of the JSON-schema `required` attribute.

**Closed** 2021-05-02 23:13 UTC
